version: '3.8'

services:
  server:
    build: .
    command: node dist/server.js
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  worker:
    build: .
    command: node dist/workers/email.worker.js
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    command: redis-server --maxmemory-policy noeviction
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
